version: '2'
services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.2-debian-10'
#    volumes:
#      - 'mongodb_data:/bitnami'
  parse:
    image: 'docker.io/bitnami/parse:4-debian-10'
    ports:
      - '1337:1337'
#    volumes:
#      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '80:4040'
    environment:
      - PARSE_DASHBOARD_USER=admin
      - PARSE_DASHBOARD_PASSWORD=password
      - PARSE_HOST=localhost
#    volumes:
#      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
#volumes:
#  mongodb_data:
#    driver: local
#  parse_data:
#    driver: local
#  parse_dashboard_data:
#    driver: local
